### PR TITLE
Adding purge method to the inmemory store

### PR DESCRIPTION
**Pull request by ArchDev**
Hi. I just saw an issue and would like to help with it: GH-13

There is not so much information about it, so I will just ask questions here:
1) As I understand you prefer to test store implementation through log tests. Should we have a possibility to reset the log, so then it will be possible to test store through it. Or should I write a test for memory-store that will check it?
2) Wdyt, is it okay that I just unlink data from the store and pray for GC or I should iterate with 'delete' operator overall data?

### CODE REVIEW

**Comment by ai** [comment]
:D. Not so easy ;).

1. You need to check out the standard name across the ecosystem. The standard name is `destroy`.
2. Standard mean, that it should be documented in `Store` methods list.
3. There is also second `IndexedStore` in `logux-client`

**Comment by ArchDev** [comment]
Isn't it strange that all Stores are not in the same package?

**Comment by ai** [comment]
@ArchDev anyone could write a store. So it is always will be the case when there is a store out the core package.

Right now IndexedDB store placed at `logux-client` since it is browser’s specific thing. In another hand, in the future SQL store will be placed to `logux-server.

**Comment by ai** [comment]
Other notes:

3. Every standard method must have tests in `each-store-test.js`. 
4. Always call `npm test` before sending PR.

**Comment by ai** [comment]
We are closer to finish:

1. Add docs to JSDoc. You can find it at `index.js`.
2. Tests must also test cleaning `lastX` properties.

**Comment by ai** [comment]
Thanks

**Pull request merged**
